#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectDir = path.resolve(__dirname, '..');
const wasmPath = path.join(projectDir, 'contracts', 'MyNFT.wasm');
const outputPath = path.join(projectDir, 'src', 'nft', 'generated', 'MyNFTWasm.ts');

if (!fs.existsSync(wasmPath)) {
    console.error(`ERROR: Missing WASM file: ${wasmPath}`);
    console.error('Run: cd contracts && npm run build:nft:copy');
    process.exit(1);
}

const wasmBuffer = fs.readFileSync(wasmPath);
const base64 = wasmBuffer.toString('base64');

const chunkSize = 120;
const chunks = [];
for (let i = 0; i < base64.length; i += chunkSize) {
    chunks.push(base64.slice(i, i + chunkSize));
}

const content = `/* eslint-disable */
// Auto-generated by backend/scripts/embed-wasm.mjs
// Source: backend/contracts/MyNFT.wasm

const MY_NFT_WASM_BASE64 = [
${chunks.map((chunk) => `    '${chunk}'`).join(',\n')}
].join('');

let cachedBytecode: Uint8Array | null = null;

function decodeBase64ToBytes(data: string): Uint8Array {
    if (typeof Buffer !== 'undefined') {
        return Uint8Array.from(Buffer.from(data, 'base64'));
    }

    if (typeof atob !== 'undefined') {
        const binary = atob(data);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }
        return bytes;
    }

    throw new Error('No base64 decoder available in current runtime');
}

export function getMyNftBytecode(): Uint8Array {
    if (!cachedBytecode) {
        cachedBytecode = decodeBase64ToBytes(MY_NFT_WASM_BASE64);
    }

    return new Uint8Array(cachedBytecode);
}
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, content, 'utf8');

console.log(`Embedded MyNFT.wasm -> ${outputPath}`);
console.log(`WASM bytes: ${wasmBuffer.length}`);
